### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by Isaac96** [fromScratchEd/ShrimpKey_rev2#29]
Compiling for the ShrimpUSB 328 fails with a "Selected board depends on 'arduino' core (not installed)." error. I am using 1.6.5 r2.

**Comment by sdmeijer** [comment]
Please try Arduino IDE 1.0.6
https://www.arduino.cc/en/Main/OldSoftwareReleases#previous

**Comment by Isaac96** [comment]
OK, thanks a lot! Compiles fine!
